import { NextRequest, NextResponse } from 'next/server'
import { fetchItem, updateItem } from '@/lib/supabase'
import { MODULE_MAP } from '@/lib/constants'
import type { Module } from '@/lib/types'

export const dynamic = 'force-dynamic'

function generateFigrSpec(item: {
  title: string
  detail: string | null
  module: string
  owner: string
  priority: string
  customers: string[]
}): string {
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const moduleName = MODULE_MAP[item.module as Module] ?? item.module
  const ownerName = item.owner.charAt(0).toUpperCase() + item.owner.slice(1)
  const customers = item.customers?.length ? item.customers.join(', ') : '—'

  return `# Figr Prototype Spec: ${item.title}

| Field | Value |
|-------|-------|
| **Owner** | ${ownerName} |
| **Module** | ${moduleName} |
| **Priority** | ${item.priority.toUpperCase()} |
| **Customers** | ${customers} |
| **Created** | ${date} |

---

## Overview

${item.detail || '_Add a brief description of what this prototype should demonstrate._'}

---

## Screens to Design

List every screen required for this prototype:

| # | Screen Name | Purpose | Entry Point |
|---|-------------|---------|-------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |

---

## User Flow

Map the complete journey through the prototype:

\`\`\`
[Entry Point]
    ↓
[Screen 1: ___________]  →  [Screen 2: ___________]
    ↓                              ↓
[Error State]            [Success / Confirmation]
\`\`\`

---

## Key Interactions

| Trigger | Element | Behaviour | Transition |
|---------|---------|-----------|------------|
| Tap / Click | | | |
| Hover | | | |
| Input | | | |
| Scroll | | | |

---

## Component Inventory

List every new or modified component needed:

- [ ] (New component)
- [ ] (Modified component)
- [ ] (Reuse existing — specify which)

---

## States & Variants

| Component | States Required |
|-----------|----------------|
| | default, hover, active, disabled |
| | loading, empty, error, success |
| | |

---

## Design Tokens

Use Zocket's design system tokens:

| Token | Value |
|-------|-------|
| Primary | \`#2563EB\` |
| Surface | \`#FFFFFF\` |
| Background | \`#F9FAFB\` |
| Border | \`#E5E7EB\` |
| Text primary | \`#111827\` |
| Text muted | \`#6B7280\` |
| Border radius (card) | \`12px\` |
| Border radius (button) | \`8px\` |
| Font | Inter |
| Spacing grid | \`4px\` |

---

## Annotations for Engineering

Notes the prototype should make explicit for handoff:

1.
2.
3.

---

## Assets Required

- [ ] Icons (list which ones)
- [ ] Illustrations
- [ ] Product screenshots / mockup images
- [ ] Brand assets (logo, colours)

---

## Acceptance Criteria for Prototype Review

Before handing off to engineering, the prototype must demonstrate:

- [ ]
- [ ]
- [ ]

---

_Upload this file to Figr as the brief for your prototype._
_Once the prototype is ready, paste the Figr link back into the backlog item._
_Generated by Zocket Backlog · ${date}_
`
}

export async function POST(req: NextRequest) {
  const { item_id } = await req.json()
  if (!item_id) return NextResponse.json({ error: 'item_id required' }, { status: 400 })

  const item = await fetchItem(item_id)
  if (!item) return NextResponse.json({ error: 'Item not found' }, { status: 404 })

  const content = generateFigrSpec(item)
  const drive_url = 'https://drive.google.com/drive/folders/1VU8xCkvfwMbkyxNFXR1MUMG77LvAPjVz'
  const created_at = new Date().toISOString()

  const updatedWorkflow = {
    ...(item.workflow ?? {}),
    figr: {
      ...(item.workflow?.figr ?? {}),
      spec_content: content,
      drive_url,
      created_at,
    },
  }
  await updateItem(item_id, { workflow: updatedWorkflow })

  return NextResponse.json({ content, drive_url, created_at })
}
