import { NextRequest, NextResponse } from 'next/server'
import { fetchItem, updateItem } from '@/lib/supabase'
import { MODULE_MAP } from '@/lib/constants'
import type { Module } from '@/lib/types'

export const dynamic = 'force-dynamic'

function generatePRD(item: {
  title: string
  detail: string | null
  module: string
  owner: string
  priority: string
  status: string
  linear_id: string | null
  customers: string[]
}): string {
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  const moduleName = MODULE_MAP[item.module as Module] ?? item.module
  const ownerName = item.owner.charAt(0).toUpperCase() + item.owner.slice(1)
  const customers = item.customers?.length ? item.customers.join(', ') : '—'
  const linear = item.linear_id ? `[${item.linear_id}](https://linear.app/zocket-tech/issue/${item.linear_id})` : 'Not yet created'
  const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60)

  return `# PRD: ${item.title}

| Field | Value |
|-------|-------|
| **Owner** | ${ownerName} |
| **Module** | ${moduleName} |
| **Priority** | ${item.priority.toUpperCase()} |
| **Status** | ${item.status} |
| **Linear** | ${linear} |
| **Customers** | ${customers} |
| **Created** | ${date} |

---

## 1. Problem Statement

${item.detail || '_No description provided. Add context here._'}

---

## 2. Goals

- [ ] Define the primary outcome this feature achieves
- [ ] Identify what user behaviour changes
- [ ] Align on business impact (retention / revenue / efficiency)

---

## 3. Success Metrics

| Metric | Baseline | Target | How to Measure |
|--------|----------|--------|----------------|
| | — | — | |
| | — | — | |
| | — | — | |

---

## 4. User Stories

> **As a** [user type],
> **I want to** [action],
> **so that** [outcome].

Add all key user stories below:

1.
2.
3.

---

## 5. Scope

### In Scope
-

### Out of Scope
-

---

## 6. Functional Requirements

### Core Requirements
1.
2.
3.

### Edge Cases & Error States
1.
2.

---

## 7. Non-Functional Requirements

- **Performance:** Response time < 2s for key interactions
- **Accessibility:** WCAG AA compliant
- **Mobile:** Responsive / native parity where applicable
- **Security:** No PII exposed in logs or URLs

---

## 8. Design

- Figr prototype: _[ link to be added after prototype is created ]_
- Key screens:
- Design tokens: follow Zocket design system

---

## 9. Open Questions

| # | Question | Owner | Due | Status |
|---|----------|-------|-----|--------|
| 1 | | ${ownerName} | | Open |
| 2 | | | | Open |

---

## 10. Timeline

| Milestone | Target Date | Owner |
|-----------|-------------|-------|
| PRD sign-off | | ${ownerName} |
| Figr prototype | | |
| Dev kickoff | | |
| QA complete | | |
| Launch | | |

---

## 11. Dependencies

- [ ] List any upstream dependencies
- [ ] Cross-team dependencies
- [ ] Third-party services or APIs

---

_Generated by Zocket Backlog · ${date}_
_Wiki path: \`wiki/prds/${slug}.md\`_
`
}

export async function POST(req: NextRequest) {
  const { item_id } = await req.json()
  if (!item_id) return NextResponse.json({ error: 'item_id required' }, { status: 400 })

  const item = await fetchItem(item_id)
  if (!item) return NextResponse.json({ error: 'Item not found' }, { status: 404 })

  const content = generatePRD(item)
  const slug = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60)
  const wiki_path = `wiki/prds/${slug}.md`
  const drive_url = 'https://drive.google.com/drive/folders/1jl0idgmxGn3kncuf8oIf5yQZnv2dBAYP'
  const created_at = new Date().toISOString()

  const updatedWorkflow = {
    ...(item.workflow ?? {}),
    prd: { wiki_path, drive_url, created_at, content },
  }
  await updateItem(item_id, { workflow: updatedWorkflow })

  return NextResponse.json({ wiki_path, drive_url, created_at, content })
}
